name: paseo_mobile
description: App Flutter de Paseo Points (movil, web comercio, web administracion).
publish_to: none
resolution: workspace
environment:
  sdk: ^3.13.0

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^11.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
